# Generated by Django 6.1.1 on 2026-09-29 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('phone', models.CharField(max_length=20, verbose_name='teléfono')),
                ('institutional_email', models.EmailField(max_length=254, verbose_name='correo institucional')),
                ('university', models.CharField(max_length=200, verbose_name='universidad')),
                ('university_acronym', models.CharField(max_length=20, verbose_name='siglas de universidad')),
                ('career', models.CharField(max_length=200, verbose_name='carrera')),
                ('required_hours', models.PositiveIntegerField(verbose_name='horas a cumplir')),
                ('cv', models.FileField(upload_to='collaborators/cv/', verbose_name='CV')),
                ('university_id', models.FileField(upload_to='collaborators/university_id/', verbose_name='credencial universitaria')),
                ('application_status', models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_REVIEW', 'En revisión'), ('NEEDS_CORRECTION', 'Requiere corrección'), ('APPROVED', 'Aprobado')], default='DRAFT', max_length=30, verbose_name='estado de solicitud')),
                ('correction_reason', models.TextField(blank=True, verbose_name='motivo de corrección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
