# Generated by Django 6.1.1 on 2026-10-08 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_collaboratorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='número de generación')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=10, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de cierre')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de asignación')),
                ('collaborator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generation_membership', to='accounts.collaboratorprofile', verbose_name='colaborador')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='onboarding.generation', verbose_name='generación')),
            ],
        ),
    ]
